# Used: https://codeberg.org/TheEvilSkeleton/flatpak-hello-world
steps:
  build:
    image: alpine
    secrets: [access_token]
    when:
      branch: main
      event: [push, pull_request, tag]
    commands:
      - apk add flatpak flatpak-builder
      - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - ls -la
      - flatpak-builder --disable-rofiles-fuse --install-deps-from=flathub --default-branch=master --force-clean --repo=build-repo build-dir build-aux/flatpak/page.codeberg.SOrg.DogGTK.Devel.json
      - flatpak build-bundle build-repo page.codeberg.SOrg.DogGTK.Devel.flatpak page.codeberg.SOrg.DogGTK.Devel