on:
  push:
    branches: [main]
  pull_request:
name: Nightly Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - run: ls
