on:
  push:
    branches: [main]
  pull_request:
name: Nightly Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - run: git clone https://codeberg.org/SOrg/Doggo.git repo && cd repo && flatpak-builder --user --disable-rofiles-fuse --repo=repo --force-clean build-dir build-aux/flatpak/page.codeberg.SOrg.DogGTK.Devel.json && flatpak build-bundle repo page.codeberg.SOrg.DogGTK.Devel.flatpak page.codeberg.SOrg.DogGTK.Devel
